version: '3.5'

services:
  # database
  db:
    container_name: autodata_db
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - db_data:/var/lib/mysql
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autodata
      MYSQL_USER: autodata
      MYSQL_PASSWORD: autodata
    networks:
      - autodata
  # phpmyadmin
  phpmyadmin:
    container_name: autodata_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - autodata

networks:
  autodata:
    name: 'autodata'

volumes:
  db_data:
