version: '3.5'

services:
  # database
  db:
    container_name: autodata_db
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - db_data:/var/lib/mysql
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
    networks:
      - autodata
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  # phpmyadmin
  phpmyadmin:
    container_name: autodata_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    networks:
      - autodata
  # ingest
  ingest:
    container_name: autodata_ingest
    depends_on:
      - db
    build:
      context: ingest/
    volumes:
      - ./ingest/data:/usr/src/data
    restart: 'no'
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
    networks:
      - autodata

networks:
  autodata:
    name: 'autodata'

volumes:
  db_data:
